### ISSUE TITLE
Job submission exception File not found but data file is there

### ISSUE THREAD

**Issue by etsangsplk** [ververica/flink-training-exercises#40]
I am  using the web Ui to submit a first test job

com.dataartisans.flinktraining.exercises.datastream_java.basics.RideCleansingExercise 

-input /Users/etsang/dev/src/github.com/apache/flink/flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT/examples/data/nycTaxiRides.gz

ls /Users/etsang/dev/src/github.com/apache/flink/flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT/examples/data/nycTaxiRides.gz is able to find the file

```java.io.FileNotFoundException: /Users/etsang/dev/src/github.com/apache/flink/flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT/examples/data/nycTaxiRides.gz (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.dataartisans.flinktraining.exercises.datastream_java.sources.TaxiRideSource.run(TaxiRideSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by rmetzger** [comment]
Are you running Flink on the same machine, or on some remote server, local virtual machine or docker container?

**Comment by etsangsplk** [comment]
@rmetzger I think I can close this. The reason is the file is a symbink created by the system and I jsut put the data file in it without aware it is just a link to the folder. ls and such supports link, but not the java api.
